### ISSUE TITLE
ProdectResultsetMapper can not handle  List[Int] as the return type from dao function.

### ISSUE THREAD

**Issue by H-Mehra** [datasift/dropwizard-scala#19]
while returning the List[Int] from the JDBI dao I see following exception please help.

Following is the code snap -

@UseStringTemplate3StatementLocator
abstract class RelationalDao () {
    
  @SqlQuery("SELECT * FROM \<resourceName\>;")
  def getList(@Define("resourceName") resourceName: String): List[Int]  
}

resulting in below exception. 

ERROR [2017-02-08 21:52:46,803] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 7fc7ab8663f6e79d
! java.lang.InstantiationException: null
! at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
! at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
! at com.datasift.dropwizard.scala.jdbi.tweak.ProductResultSetMapper.map(ProductResultSetMapperFactory.scala:79)
! ... 74 common frames omitted
! Causing: java.lang.IllegalArgumentException: Cannot create instances of abstract class: List
! at com.datasift.dropwizard.scala.jdbi.tweak.ProductResultSetMapper.map(ProductResultSetMapperFactory.scala:85)
! at com.datasift.dropwizard.scala.jdbi.tweak.ProductResultSetMapper.map(ProductResultSetMapperFactory.scala:22)
! at org.skife.jdbi.v2.RegisteredMapper.map(RegisteredMapper.java:35)

**Comment by nicktelford** [comment]
This is actually broken due to a design constraint in jDBI: all "collection" types (i.e. to return multiple rows) need to implement `java.util.Iterable`, which Scala's collections don't. Unfortunately, there's no way to solve this without major changes to jDBI upstream.

For now, I recommend making `java.util.List[Int]` your return type, then having another method that converts it to a Scala `List`:
