### ISSUE TITLE
Support dropwizard 0.8.0

### ISSUE THREAD

**Issue by plalloni** [datasift/dropwizard-scala#4]
Currently dropwizard-scala does not works against dropwizard 0.8.0.

**Comment by mikemoraned** [comment]
@nicktelford : any plans to upgrade to 0.8.0 or 0.8.1? I started looking into what it would take. Some notes:
* It looks like OptionResourceMethodDispatchAdapter can be replaced by a https://jax-rs-spec.java.net/nonav/2.0-rev-a/apidocs/javax/ws/rs/container/ContainerResponseFilter.html (since it has access to the entity and the status)
* InjectableProvider usage can be replaced with some sort of binder (based on https://jersey.java.net/documentation/latest/migration.html#mig-server-api)

**Comment by torbjornvatn** [comment]
I gave this a stab, but couldn't wrap my head around how to convert the inject code to the new HK2 style of doing things.
Would have been really nice to get 0.8.x support though.

**Comment by maximn** [comment]
Latest version now is - 0.9.1

**Comment by nicktelford** [comment]
Sorry this has taken me so long. Going forward, I plan to maintain this for the new releases of Dropwizard for however long is feasible.

Releases have now been made, and are available on Maven Central, for `0.8.5` and `0.9.2`. `master` has been updated for `1.0.0-rc2`, but I won't cut a release until `1.0.0` final is released.
